"""Generate Flutter widget code from a UI screen-spec JSON.

Produces a single self-contained Flutter/Dart file that uses a Stack +
Positioned layout mirroring the original Unity UI hierarchy.  All
coordinates are expressed as percentage-based fractions of the canvas so
the widget scales correctly on any device.

Usage::

    from il2cpp_recovery_studio.ui_extractor.flutter_codegen import FlutterCodeGen
    gen = FlutterCodeGen()
    dart_src = gen.generate(screen_json)
    Path("lib/screens/main_screen.dart").write_text(dart_src)
"""
from __future__ import annotations

import re
from pathlib import Path
from textwrap import indent as _indent
from typing import Optional


# ── name helpers ─────────────────────────────────────────────────────────────

def _to_camel(name: str) -> str:
    """'btn_play_now' -> 'btnPlayNow'"""
    parts = re.split(r"[^a-zA-Z0-9]+", name)
    if not parts:
        return "element"
    return parts[0].lower() + "".join(p.capitalize() for p in parts[1:])


def _to_pascal(name: str) -> str:
    """'main_screen' -> 'MainScreen'"""
    parts = re.split(r"[^a-zA-Z0-9]+", name)
    return "".join(p.capitalize() for p in parts if p)


def _color_to_dart(color: Optional[dict]) -> str:
    if not color:
        return "Colors.transparent"
    r = int(color.get("r", 1) * 255)
    g = int(color.get("g", 1) * 255)
    b = int(color.get("b", 1) * 255)
    a = int(color.get("a", 1) * 255)
    if a == 255:
        return f"Color(0xFF{r:02X}{g:02X}{b:02X})"
    return f"Color(0x{a:02X}{r:02X}{g:02X}{b:02X})"


def _align_to_dart(alignment: str) -> str:
    _MAP = {
        "UpperLeft": "Alignment.topLeft",
        "UpperCenter": "Alignment.topCenter",
        "UpperRight": "Alignment.topRight",
        "MiddleLeft": "Alignment.centerLeft",
        "MiddleCenter": "Alignment.center",
        "MiddleRight": "Alignment.centerRight",
        "LowerLeft": "Alignment.bottomLeft",
        "LowerCenter": "Alignment.bottomCenter",
        "LowerRight": "Alignment.bottomRight",
    }
    return _MAP.get(alignment, "Alignment.center")


class FlutterCodeGen:
    """Generate a Flutter Dart file from a screen-spec dict."""

    def generate(self, screen_json: dict, class_suffix: str = "") -> str:
        """Return a complete Dart source string for the screen."""
        screen_name = screen_json.get("screen_name", "UnknownScreen")
        canvas = screen_json.get("canvas_size", {"width": 1080, "height": 1920})
        elements = screen_json.get("elements", [])
        manifest = screen_json.get("asset_manifest", {})

        cw = float(canvas.get("width", 1080))
        ch = float(canvas.get("height", 1920))

        class_name = _to_pascal(screen_name) + (class_suffix or "Screen")

        # Collect button names for handler stubs
        button_names = [
            el.get("name", el.get("id", "btn"))
            for el in elements
            if el.get("type") == "Button"
        ]

        sprites = manifest.get("sprites_used", [])
        fonts = manifest.get("fonts_used", [])

        lines: list[str] = []

        # File header
        lines += [
            f"// AUTO-GENERATED by IL2CPP Recovery Studio — FlutterCodeGen",
            f"// Screen : {screen_name}",
            f"// Canvas : {int(cw)} x {int(ch)} px",
            f"// Elements: {len(elements)}",
            "",
            "import 'package:flutter/material.dart';",
            "",
        ]

        if sprites:
            lines.append("// ── Sprite asset paths ────────────────────────────────────")
            for sp in sprites:
                const_name = _to_camel(Path(sp).stem) + "Sprite"
                lines.append(f"const String {const_name} = '{sp}';")
            lines.append("")

        # Widget class
        lines += [
            f"class {class_name} extends StatelessWidget {{",
            f"  const {class_name}({{super.key}});",
            "",
            "  @override",
            "  Widget build(BuildContext context) {",
            "    return LayoutBuilder(",
            "      builder: (context, constraints) {",
            f"        final double cw = constraints.maxWidth;",
            f"        final double ch = constraints.maxHeight;",
            "        return Stack(",
            "          children: [",
        ]

        for el in elements:
            if not el.get("active", True):
                continue
            widget_lines = self._element_to_positioned(el, cw, ch)
            for wl in widget_lines:
                lines.append(f"            {wl}")

        lines += [
            "          ],",
            "        );",
            "      },",
            "    );",
            "  }",
            "",
        ]

        # Button handler stubs
        if button_names:
            lines.append("  // ── Button handlers (implement these) ───────────────")
            for btn in button_names:
                handler = f"on{_to_pascal(btn)}Pressed"
                lines += [
                    f"  void {handler}() {{",
                    f"    // TODO: implement {handler}",
                    "  }",
                    "",
                ]

        lines.append("}")

        return "\n".join(lines)

    def generate_to_file(self, screen_json: dict, output_path: Path) -> Path:
        """Generate and write a Dart file.  Returns the written path."""
        output_path = Path(output_path)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(self.generate(screen_json), encoding="utf-8")
        return output_path

    # ── element → Positioned widget ─────────────────────────────────────

    def _element_to_positioned(self, el: dict, cw: float, ch: float) -> list[str]:
        """Convert one element dict to Positioned(...) widget source lines."""
        pos = el.get("position", {"x": 0, "y": 0})
        size = el.get("size", {"width": 0, "height": 0})
        w = float(size.get("width", 0))
        h = float(size.get("height", 0))

        # Convert Unity centre-origin Y-up to top-left Y-down
        left = cw / 2 + pos.get("x", 0) - w / 2
        top = ch / 2 - pos.get("y", 0) - h / 2

        # Express as fractions so layout is resolution-independent
        lf = left / cw if cw else 0
        tf = top / ch if ch else 0
        wf = w / cw if cw else 0
        hf = h / ch if ch else 0

        inner = self._element_inner_widget(el)
        el_name = el.get("name", el.get("id", "element"))
        comment = f"// {el_name} ({el.get('type', '?')})"

        return [
            comment,
            "Positioned(",
            f"  left: cw * {lf:.6f},",
            f"  top: ch * {tf:.6f},",
            f"  width: cw * {wf:.6f},",
            f"  height: ch * {hf:.6f},",
            f"  child: {inner},",
            "),",
        ]

    def _element_inner_widget(self, el: dict) -> str:
        el_type = el.get("type", "Empty")
        color = el.get("color")
        sprite_file = el.get("sprite_file", "") or el.get("sprite_name", "")

        if el_type == "Image" and sprite_file:
            return (
                f"Image.asset('{sprite_file}', fit: BoxFit.fill, "
                f"color: {_color_to_dart(color)})"
            ) if color and color.get("a", 1) < 1.0 else f"Image.asset('{sprite_file}', fit: BoxFit.fill)"

        if el_type == "RawImage" and sprite_file:
            return f"Image.asset('{sprite_file}', fit: BoxFit.fill)"

        if el_type == "Text":
            text = el.get("text", "").replace("'", "\\'").replace("\n", "\\n")
            fs = el.get("font_size", 14)
            align_str = el.get("alignment", "MiddleCenter")
            dart_align = _align_to_dart(align_str)
            c_dart = _color_to_dart(color)
            return (
                f"Text('{text}', "
                f"style: TextStyle(fontSize: {fs}.0, color: {c_dart}), "
                f"textAlign: TextAlign.center)"
            )

        if el_type == "Button":
            label = el.get("label", "")
            label_escaped = label.replace("'", "\\'").replace("\n", "\\n")
            btn_name = el.get("name", el.get("id", "btn"))
            handler = f"on{_to_pascal(btn_name)}Pressed"
            normal_color = _color_to_dart(el.get("normal_color"))
            label_color = _color_to_dart(el.get("label_color"))
            fs = el.get("label_font_size", 24)
            if label:
                return (
                    f"ElevatedButton("
                    f"onPressed: {handler}, "
                    f"style: ElevatedButton.styleFrom(backgroundColor: {normal_color}, "
                    f"shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(6))), "
                    f"child: Text('{label_escaped}', style: TextStyle(fontSize: {fs}.0, color: {label_color})))"
                )
            return (
                f"ElevatedButton("
                f"onPressed: {handler}, "
                f"style: ElevatedButton.styleFrom(backgroundColor: {normal_color}), "
                f"child: const SizedBox.shrink())"
            )

        if el_type == "InputField":
            placeholder = el.get("text", "")
            return f"TextField(decoration: InputDecoration(hintText: '{placeholder}'))"

        if el_type == "Toggle":
            is_on = "true" if el.get("is_on", False) else "false"
            return f"Switch(value: {is_on}, onChanged: (_) {{}})"

        if el_type == "Slider":
            val = el.get("value", 0.0)
            mn = el.get("min_value", 0.0)
            mx = el.get("max_value", 1.0)
            return f"Slider(value: {val}, min: {mn}, max: {mx}, onChanged: (_) {{}})"

        if el_type == "ScrollRect":
            return "SingleChildScrollView(child: Column(children: []))"

        if el_type in ("Empty", "CanvasGroup") or not el_type:
            if color and any(color.get(k, 0) > 0 for k in ("r", "g", "b")):
                return f"Container(color: {_color_to_dart(color)})"
            return "SizedBox.shrink()"

        # Generic fallback: colored container with tooltip
        return f"Container(color: {_color_to_dart(color)})  // {el_type}"
