"""Generate a Flutter widget file from a UI screen-spec JSON.

Produces a single ``StatelessWidget`` containing a ``Stack`` of
``Positioned`` children with percentage-based sizing.  Every element type
(Image, Text, Button, RawImage, Toggle, Slider, InputField, etc.) gets
mapped to the closest Flutter equivalent.

Usage::

    from il2cpp_recovery_studio.ai_export.flutter_codegen import FlutterCodeGen
    code = FlutterCodeGen().generate(screen_json)
    Path("lib/screens/main_screen.dart").write_text(code)
"""
from __future__ import annotations

import re
from pathlib import Path
from typing import Optional


class FlutterCodeGen:
    """Generate a Flutter Dart widget from a screen-spec dict."""

    # ── public ───────────────────────────────────────────────────────────────

    def generate(self, screen_json: dict, class_name: Optional[str] = None) -> str:
        """Return a Dart source string for the screen."""
        name = screen_json.get("screen_name", "UnknownScreen")
        if class_name is None:
            class_name = self._to_class_name(name)

        canvas = screen_json.get("canvas_size", {"width": 1080, "height": 1920})
        cw = float(canvas.get("width", 1080))
        ch = float(canvas.get("height", 1920))

        elements = screen_json.get("elements", [])
        # Only render top-level children (parent_id == None) as Positioned;
        # nested children are handled by their parent's build method.
        # For simplicity we render ALL active elements as a flat Stack
        # (matches the Unity flat-Canvas model).
        active_elements = [e for e in elements if e.get("active", True)]

        bg = screen_json.get("background_color", {"r": 0, "g": 0, "b": 0, "a": 1})
        bg_color = self._color(bg)

        # imports
        lines: list[str] = [
            "// AUTO-GENERATED by IL2CPP Recovery Studio — DO NOT EDIT",
            f"// Screen: {name}  |  Canvas: {int(cw)}x{int(ch)}",
            "",
            "import 'package:flutter/material.dart';",
            "",
        ]

        # Widget class
        lines += [
            f"class {class_name} extends StatelessWidget {{",
            f"  const {class_name}({{Key? key}}) : super(key: key);",
            "",
            "  @override",
            "  Widget build(BuildContext context) {",
            "    return LayoutBuilder(",
            "      builder: (context, constraints) {",
            "        final double cw = constraints.maxWidth;",
            "        final double ch = constraints.maxHeight;",
            "        return Container(",
            f"          color: {bg_color},",
            "          child: Stack(",
            "            children: [",
        ]

        for el in active_elements:
            child_lines = self._element_to_positioned(el, cw, ch)
            for cl in child_lines:
                lines.append("              " + cl)

        lines += [
            "            ],",
            "          ),",
            "        );",
            "      },",
            "    );",
            "  }",
        ]

        # Button handler stubs
        buttons = [e for e in active_elements if e.get("type") == "Button"]
        if buttons:
            lines.append("")
            for btn in buttons:
                handler = self._handler_name(btn.get("name", btn.get("id", "btn")))
                lines.append(f"  void {handler}() {{")
                lines.append(f"    // TODO: implement {handler}")
                lines.append("  }")

        lines.append("}")
        lines.append("")  # trailing newline

        return "\n".join(lines)

    # ── element → Positioned widget ──────────────────────────────────────────

    def _element_to_positioned(self, el: dict, cw: float, ch: float) -> list[str]:
        """Return lines for a Positioned widget wrapping the element's widget."""
        pos = el.get("position", {"x": 0, "y": 0})
        size = el.get("size", {"width": 0, "height": 0})

        # Convert Unity anchoredPosition (center, Y-up) → top-left, Y-down px
        left = cw / 2 + pos.get("x", 0) - size.get("width", 0) / 2
        top = ch / 2 - pos.get("y", 0) - size.get("height", 0) / 2
        w = size.get("width", 0)
        h = size.get("height", 0)

        # Convert to percentages so the widget scales with the LayoutBuilder
        left_pct = left / cw if cw else 0
        top_pct = top / ch if ch else 0
        w_pct = w / cw if cw else 0
        h_pct = h / ch if ch else 0

        inner = self._inner_widget(el)
        comment = f"// {el.get('name', el.get('id', '?'))} [{el.get('type', '?')}]"

        rotation = el.get("rotation", 0.0)
        scale_x = el.get("scale", {}).get("x", 1.0)
        scale_y = el.get("scale", {}).get("y", 1.0)
        needs_transform = abs(rotation) > 0.01 or abs(scale_x - 1.0) > 0.01 or abs(scale_y - 1.0) > 0.01

        lines = [comment]
        lines.append("Positioned(")
        lines.append(f"  left: cw * {left_pct:.6f},")
        lines.append(f"  top: ch * {top_pct:.6f},")
        lines.append(f"  width: cw * {w_pct:.6f},")
        lines.append(f"  height: ch * {h_pct:.6f},")

        if needs_transform:
            angle_rad = rotation * 3.14159265358979 / 180.0
            lines.append("  child: Transform(")
            lines.append(f"    transform: Matrix4.identity()")
            if abs(rotation) > 0.01:
                lines.append(f"      ..rotateZ({angle_rad:.6f})")
            if abs(scale_x - 1.0) > 0.01 or abs(scale_y - 1.0) > 0.01:
                lines.append(f"      ..scale({scale_x:.4f}, {scale_y:.4f}),")
            else:
                lines[-1] += ","
            lines.append("    alignment: Alignment.center,")
            lines.append(f"    child: {inner},")
            lines.append("  ),")
        else:
            lines.append(f"  child: {inner},")

        lines.append("),")
        return lines

    def _inner_widget(self, el: dict) -> str:
        """Return the Flutter widget string for an element's type."""
        t = el.get("type", "Empty")

        if t == "Image":
            sprite = el.get("sprite_file", "") or el.get("sprite_name", "")
            color = el.get("color", {})
            color_str = self._color(color)
            if sprite:
                safe = Path(sprite).name
                return (
                    f"Image.asset('assets/sprites/{safe}', "
                    f"fit: BoxFit.fill, color: {color_str} == Colors.white ? null : {color_str})"
                )
            return f"Container(color: {color_str})"

        if t == "RawImage":
            tex = el.get("texture_name", "")
            color = self._color(el.get("color", {}))
            if tex:
                return f"Image.asset('assets/sprites/{tex}.png', fit: BoxFit.fill)"
            return f"Container(color: {color})"

        if t == "Text":
            text = self._dart_string(el.get("text", ""))
            fs = el.get("font_size", 14)
            color = self._color(el.get("color", {}))
            style = el.get("font_style", "Normal")
            align = self._text_align(el.get("alignment", "MiddleCenter"))
            weight = "FontWeight.bold" if "Bold" in style else "FontWeight.normal"
            italic = "FontStyle.italic" if "Italic" in style else "FontStyle.normal"
            return (
                f"Text({text}, textAlign: {align}, "
                f"style: TextStyle(fontSize: {fs}.0, color: {color}, "
                f"fontWeight: {weight}, fontStyle: {italic}))"
            )

        if t == "Button":
            label = self._dart_string(el.get("label", ""))
            normal = self._color(el.get("normal_color", {}))
            pressed = self._color(el.get("pressed_color", {}))
            handler = self._handler_name(el.get("name", el.get("id", "btn")))
            return (
                f"ElevatedButton(onPressed: {handler}, "
                f"style: ElevatedButton.styleFrom("
                f"backgroundColor: {normal}, "
                f"foregroundColor: Colors.white, "
                f"shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(6))), "
                f"child: Text({label}))"
            )

        if t == "Toggle":
            is_on = "true" if el.get("is_on", False) else "false"
            return f"Checkbox(value: {is_on}, onChanged: (_) {{}})"

        if t == "Slider":
            val = el.get("value", 0.0)
            mn = el.get("min_value", 0.0)
            mx = el.get("max_value", 1.0)
            return f"Slider(value: {val}, min: {mn}, max: {mx}, onChanged: (_) {{}})"

        if t == "InputField":
            hint = self._dart_string(el.get("text", ""))
            return f"TextField(decoration: InputDecoration(hintText: {hint}))"

        if t == "ScrollRect":
            return "SingleChildScrollView(child: SizedBox())"

        if t in ("Outline", "Shadow"):
            color = self._color(el.get("effect_color", {}))
            return f"Container(decoration: BoxDecoration(boxShadow: [BoxShadow(color: {color}, blurRadius: 4)]))"

        if t == "CanvasGroup":
            alpha = el.get("alpha", 1.0)
            return f"Opacity(opacity: {alpha:.3f}, child: SizedBox())"

        return "SizedBox()  // Empty / unrecognised type"

    # ── helpers ──────────────────────────────────────────────────────────────

    @staticmethod
    def _to_class_name(name: str) -> str:
        """Convert a screen name to a PascalCase Dart class name."""
        parts = re.split(r"[\s_\-]+", name)
        return "".join(p.capitalize() for p in parts if p) + "Screen"

    @staticmethod
    def _handler_name(name: str) -> str:
        """Convert an element name to a camelCase handler method name."""
        parts = re.split(r"[\s_\-]+", name)
        if not parts:
            return "onPressed"
        result = parts[0].lower() + "".join(p.capitalize() for p in parts[1:])
        return f"on{result.capitalize()}Pressed"

    @staticmethod
    def _color(c: dict) -> str:
        """Convert a Unity RGBA dict (0-1 floats) to Flutter Color(0xAARRGGBB)."""
        r = max(0, min(255, int(c.get("r", 1) * 255)))
        g = max(0, min(255, int(c.get("g", 1) * 255)))
        b = max(0, min(255, int(c.get("b", 1) * 255)))
        a = max(0, min(255, int(c.get("a", 1) * 255)))
        if r == 255 and g == 255 and b == 255 and a == 255:
            return "Colors.white"
        if r == 0 and g == 0 and b == 0 and a == 255:
            return "Colors.black"
        return f"Color(0x{a:02X}{r:02X}{g:02X}{b:02X})"

    @staticmethod
    def _dart_string(s: str) -> str:
        """Escape a string for Dart source."""
        escaped = s.replace("\\", "\\\\").replace("'", "\\'").replace("\n", "\\n")
        return f"'{escaped}'"

    @staticmethod
    def _text_align(unity_align: str) -> str:
        """Map Unity TextAnchor names to Flutter TextAlign values."""
        mapping = {
            "UpperLeft": "TextAlign.left",
            "UpperCenter": "TextAlign.center",
            "UpperRight": "TextAlign.right",
            "MiddleLeft": "TextAlign.left",
            "MiddleCenter": "TextAlign.center",
            "MiddleRight": "TextAlign.right",
            "LowerLeft": "TextAlign.left",
            "LowerCenter": "TextAlign.center",
            "LowerRight": "TextAlign.right",
        }
        return mapping.get(unity_align, "TextAlign.center")
