"""HTML documentation generator: produces interactive HTML docs with navigation tree, inheritance, fields, methods, and native addresses."""
from __future__ import annotations

from pathlib import Path

from il2cpp_recovery_studio.core.logging import get_logger
from il2cpp_recovery_studio.recovery.models import RecoveredClass, RecoveredMethod, RecoveredField

logger = get_logger("docs.generator")

HTML_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>{title}</title>
<style>
body {{ font-family: monospace; margin: 0; padding: 20px; background: #1e1e1e; color: #d4d4d4; }}
h1 {{ color: #569cd6; }}
.class {{ border: 1px solid #333; margin: 10px 0; padding: 10px; background: #252526; }}
.class-header {{ color: #4ec9b0; font-weight: bold; font-size: 1.1em; }}
.field {{ color: #9cdcfe; }}
.method {{ color: #dcdcaa; }}
.namespace {{ color: #ce9178; }}
a {{ color: #569cd6; text-decoration: none; }}
a:hover {{ text-decoration: underline; }}
nav {{ background: #2d2d2d; padding: 10px; margin-bottom: 20px; border-radius: 4px; }}
.nav-item {{ margin: 2px 0; }}
.stat {{ color: #808080; }}
</style>
</head>
<body>
<h1>{title}</h1>
<p class="stat">Generated by IL2CPP Recovery Studio</p>
<div class="stat">Total classes: {total_classes} | Total methods: {total_methods}</div>
<nav>
<h3>Navigation</h3>
{nav_items}
</nav>
{content}
</body>
</html>
"""


class HTMLDocGenerator:
    """Generates HTML documentation from recovered Unity classes."""

    def generate(
        self,
        recovered_classes: list[RecoveredClass],
        output_path: str,
        title: str = "IL2CPP Recovery Documentation",
    ) -> str:
        total_methods = sum(len(rc.methods) for rc in recovered_classes)

        nav_items = []
        content_parts = []

        for rc in recovered_classes:
            full_name = f"{rc.namespace}.{rc.name}" if rc.namespace else rc.name
            anchor = full_name.replace(".", "_").replace("::", "_")
            nav_items.append(f'<div class="nav-item"><a href="#{anchor}">{full_name}</a></div>')
            content_parts.append(self._render_class(rc))

        html = HTML_TEMPLATE.format(
            title=title,
            total_classes=len(recovered_classes),
            total_methods=total_methods,
            nav_items="\n".join(nav_items),
            content="\n".join(content_parts),
        )

        out = Path(output_path)
        out.mkdir(parents=True, exist_ok=True)
        file_path = out / "index.html"
        file_path.write_text(html, encoding="utf-8")

        logger.info("Generated HTML docs: %s", file_path)
        return str(file_path)

    def _render_class(self, rc: RecoveredClass) -> str:
        full_name = f"{rc.namespace}.{rc.name}" if rc.namespace else rc.name
        anchor = full_name.replace(".", "_").replace("::", "_")
        parts = [f'<div class="class" id="{anchor}">']
        parts.append(f'<div class="class-header">{full_name}</div>')

        if rc.parent_class:
            parts.append(f'<div>Inherits: {rc.parent_class}</div>')

        if rc.fields:
            parts.append("<h4>Fields</h4>")
            for f in rc.fields:
                parts.append(f'<div class="field">{f.type_name} {f.name}</div>')

        if rc.methods:
            parts.append("<h4>Methods</h4>")
            for m in rc.methods:
                addr = f"0x{m.native_address:X}" if m.native_address else ""
                parts.append(f'<div class="method">{m.return_type} {m.name}({m.parameters}) {addr}</div>')

        parts.append("</div>")
        return "\n".join(parts)
