"""Ghidra decompilation report generator.

Produces structured Markdown reports from GhidraAnalyzer output,
formatted specifically for AI agent consumption.
"""
from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path
from typing import Optional


class GhidraReport:
    """Generate Markdown reports from decompiled method data.

    Parameters
    ----------
    output_dir:
        Where to write the generated report files.
    """

    def __init__(self, output_dir: Path) -> None:
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def generate_report(
        self,
        decompiled_methods: list[dict],
        title: str = "Ghidra Decompilation Report",
    ) -> Path:
        """Generate a Markdown report from a list of decompiled method dicts.

        Each dict should have keys: address, dotnet_signature, cpp_name,
        namespace_class, assembly, decompiled_c_code, error.

        Returns the path to the generated report file.
        """
        lines: list[str] = []
        lines.append(f"# {title}")
        lines.append("")
        lines.append(f"*Generated: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}*")
        lines.append("")
        lines.append(f"Total methods analyzed: **{len(decompiled_methods)}**")
        lines.append("")
        lines.append("> **Note for AI Agent:** The C pseudocode below is reconstructed from IL2CPP-compiled "
                     "ARM64 native code. It represents the decompiled output of Ghidra's DecompInterface "
                     "and may contain artifacts of the compilation process. Use it as a structural reference "
                     "for reconstructing the original C# logic. Variable names, types, and control flow "
                     "are approximations based on the binary analysis.")
        lines.append("")
        lines.append("---")
        lines.append("")

        successful = [m for m in decompiled_methods if not m.get("error")]
        failed = [m for m in decompiled_methods if m.get("error")]

        if successful:
            lines.append("## Successfully Decompiled Methods")
            lines.append("")
            for method in successful:
                lines.extend(self._format_method(method))

        if failed:
            lines.append("## Failed Decompilations")
            lines.append("")
            for method in failed:
                lines.append(f"### `{method.get('dotnet_signature', 'unknown')}`")
                lines.append("")
                lines.append(f"- **Address:** `0x{method.get('address', '0')}`")
                lines.append(f"- **Error:** {method.get('error', 'Unknown error')}")
                lines.append("")

        report_path = self.output_dir / "GHIDRA_REPORT.md"
        report_path.write_text("\n".join(lines), encoding="utf-8")
        return report_path

    def append_to_screen_report(
        self,
        screen_report_path: Path,
        decompiled_methods: list[dict],
    ) -> Path:
        """Append Ghidra results to an existing SCREEN_REPORT.md.

        Adds a section titled "## Native Code Analysis (Ghidra ARM64 Pseudocode)"
        with each method formatted as a code block.
        """
        existing = ""
        if screen_report_path.exists():
            existing = screen_report_path.read_text(encoding="utf-8")

        lines: list[str] = []
        if "## Native Code Analysis (Ghidra ARM64 Pseudocode)" not in existing:
            lines.append("")
            lines.append("---")
            lines.append("")
            lines.append("## Native Code Analysis (Ghidra ARM64 Pseudocode)")
            lines.append("")
            lines.append("> The following C pseudocode was generated by Ghidra's headless decompiler "
                         "analyzing the compiled ARM64 native library. Use it to understand the "
                         "runtime behavior of each method.")
            lines.append("")

        for method in decompiled_methods:
            lines.extend(self._format_method(method))

        content = existing.rstrip() + "\n" + "\n".join(lines)
        screen_report_path.write_text(content, encoding="utf-8")
        return screen_report_path

    def _format_method(self, method: dict) -> list[str]:
        """Format a single decompiled method as Markdown."""
        lines: list[str] = []
        sig = method.get("dotnet_signature", "unknown")
        address = method.get("address", "0")
        cpp_name = method.get("cpp_name", "")
        ns_class = method.get("namespace_class", "")
        assembly = method.get("assembly", "")
        c_code = method.get("decompiled_c_code", "")
        error = method.get("error")

        lines.append(f"### `{sig}`")
        lines.append("")
        lines.append(f"| Field | Value |")
        lines.append(f"|-------|-------|")
        lines.append(f"| Address | `0x{address}` |")
        if cpp_name:
            lines.append(f"| C++ Name | `{cpp_name}` |")
        if ns_class:
            lines.append(f"| Namespace.Class | `{ns_class}` |")
        if assembly:
            lines.append(f"| Assembly | `{assembly}` |")
        lines.append("")

        if error:
            lines.append(f"**Error:** {error}")
            lines.append("")
        elif c_code:
            lines.append("```c")
            lines.append(c_code.strip())
            lines.append("```")
            lines.append("")

        return lines
